### ISSUE TITLE
Lots of timeouts in R in the last week 

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1282]
I've been having intermittent issues with data downloads over the past week. One project, 355, has been impossible to download. 

I keep getting stalled somewhere on batchID 3320369 each time I try (the project collaborator who contact us had at least one occasion on batch 1522916).

I have had a couple issues with other projects, but for the most part they all work.

**Comment by ajmacdonald3** [comment]
I also had lots of timeouts trying to download complete motus metadata (`metadata(sqldb)`), but I did eventually get through a few minutes ago. For me, timeouts do not seem to be project-related, but it seems that they might be for Josh and Erica.

**Comment by cjardine-bsc** [comment]
The SQ data imports are failing with the below error: 

 org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 521; received: 0
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:200)
	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:103)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
	at org.apache.http.util.EntityUtils.consume(EntityUtils.java:88)
	at org.bsc.motus.process.SGDataImport.http(SGDataImport.java:1689)
	at org.bsc.motus.process.SGDataImport.getAuthToken(SGDataImport.java:1336)
	at org.bsc.motus.process.SGDataImport.readBatchesForAll(SGDataImport.java:893)
	at org.bsc.motus.process.SGDataImport.loop(SGDataImport.java:511)
	at org.bsc.motus.process.SGDataImport.run(SGDataImport.java:239)
	at org.bsc.motus.process.MotusJob.javaProc(MotusJob.java:76)
	at org.bsc.queue.Job.run(Job.java:343)
	
	
Don't know what this means yet. Stand by.

**Comment by denislepage** [comment]
This is the ongoing AWOOGA issue. I'm just going to close this one.

Maybe this should be our new AWOOGA call: https://twitter.com/Parody_PM/status/1583536151969038336
