### ISSUE TITLE
SG API 502 error

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#299]
The SG API that we use to pull the data into Motus is not responding as of July 6. There has been a few uploads since. Of course, Jeremy won’t be back for another week.  

2018-07-06 17:32:41 : Start Loop: 1530912461022
2018-07-06 17:32:41 : https://sgdata.motus.org/data/custom/authenticate_user?{credcleanedup}
2018-07-06 17:37:41 : The API responsed with an error (502)
HttpResponseProxy{HTTP/1.1 502 Proxy Error [Date: Fri, 06 Jul 2018 21:32:41 GMT, Server: Apache/2.4.10 (Debian), Content-Length: 521, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: text/html; charset=iso-8859-1] ResponseEntityProxy{[Content-Type: text/html; charset=iso-8859-1,Content-Length: 521,Chunked: false]}}
2018-07-06 17:37:41 : org.apache.http.HttpException: The API responsed with an error (502)
HttpResponseProxy{HTTP/1.1 502 Proxy Error [Date: Fri, 06 Jul 2018 21:32:41 GMT, Server: Apache/2.4.10 (Debian), Content-Length: 521, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: text/html; charset=iso-8859-1] ResponseEntityProxy{[Content-Type: text/html; charset=iso-8859-1,Content-Length: 521,Chunked: false]}}
2018-07-06 17:37:41 : org.apache.http.HttpException: The API responsed with an error (502)
HttpResponseProxy{HTTP/1.1 502 Proxy Error [Date: Fri, 06 Jul 2018 21:32:41 GMT, Server: Apache/2.4.10 (Debian), Content-Length: 521, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: text/html; charset=iso-8859-1] ResponseEntityProxy{[Content-Type: text/html; charset=iso-8859-1,Content-Length: 521,Chunked: false]}}
	at org.bsc.motus.process.SGDataImport.http(SGDataImport.java:1272)
	at org.bsc.motus.process.SGDataImport.getAuthToken(SGDataImport.java:1071)
	at org.bsc.motus.process.SGDataImport.readBatchesForAll(SGDataImport.java:759)
	at org.bsc.motus.process.SGDataImport.loop(SGDataImport.java:467)
	at org.bsc.motus.process.SGDataImport.run(SGDataImport.java:193)
	at org.bsc.motus.process.Job.run(Job.java:357)

**Comment by denislepage** [comment]
I checked, and the authentication on Motus appears to be responding, so the problem is likely not there.

**Comment by jbrzusto** [comment]
Do you have a record of API requests **to** motus.org from 174.140.177.36 just before 2018-07-06 17:32:41?  One of those did not complete, leaving the dataServer hung; refiling as https://github.com/jbrzusto/motusServer/issues/409

**Comment by denislepage** [comment]
Need to add this to our documentation, if not already there. Working again now. Thanks!

--
Regardless, the dataServer was restarted like so:

```
killMotusDataServer.sh
runAllMotusServers.sh   ## cleanest way to start any non-running servers on sgdata

```
(this is as user sg, which include the directory /sgm/bin in its PATH, as that is where
the two scripts are found)
