### ISSUE TITLE
SQL error: This ReceiverID is already registered to this project

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#531]
We should handle this problem more gracefully and avoid a throwing a database error in favour of a response string. I imagine the error is being caught on the Java side and displayed correctly to the user, but I would restrict database errors to problems that we potentially need to address, not based on incorrect user input.

com.microsoft.sqlserver.jdbc.SQLServerException: This ReceiverID is already registered to this project
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:314)
	at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:229)
	at org.bsc.motus.MotusBean.insertFromMap(MotusBean.java:196)
	at org.bsc.motus.MotusBean.upsertFromMap(MotusBean.java:339)
	at org.bsc.motus.MotusBean.upsert(MotusBean.java:323)
	at org.bsc.motus.RecvBean.upsertFromRequest(RecvBean.java:270)
	at org.bsc.motus.web.EditRecvServlet.doPost(EditRecvServlet.java:159)

**Comment by Hussell** [comment]
I've tried multiple times to prevent this from happening through the website, by checking to see if the receiver has already been registered before trying to do it again, but I've never been able to completely prevent it. It might be worthwhile to have a different set of eyes look at the code on that side of things.

**Comment by pmorrill** [comment]
I am tracking another issue in the recv bean - will take a look at the origin of this exception, at least.

**Comment by denislepage** [comment]
The problem is that the proc likely throws an Error. Even if you catch the error, it will still generate an email with at least the database report. If this isn’t handled correctly by Java, then the user may get sent to the error page rather than seeing a notification.

Let’s wait for Catherine to be back online. Not the highest priority for today or tomorrow.

**Comment by Hussell** [comment]
Aha! I think I found the bug. I'll test it on sandbox after the CANARIE thing.

**Comment by Hussell** [comment]
Seems to be fixed (on sandbox and beta). Caused by one missing line in RecvBean.setReceiverId, which somehow didn't break anything other than this.

**Comment by cjardine-bsc** [comment]
Perhaps we should look at using prAPIImportSensorsCTT for all receiver registrations on the website so that we have a response-code for these types of things?
