### ISSUE TITLE
API import proc error

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#71]
There is a disconnect between the number of arguments in the proc and the Java method call. Not sure which branch this applies to.

SQL = dbo.[prAPIImportTagDeployments](?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Description = list tags (Made it to result set wrapper)

Browser info:Unknown
Auth type = Unknown
Method = Unknown
Query = Unknown
Uri = Unknown
All parameters:Unknown
Stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: Procedure or function prAPIImportTagDeployments has too many arguments specified.

**Comment by denislepage** [comment]
Sorry, remaining useful portion of the stack trace.

com.microsoft.sqlserver.jdbc.SQLServerException: Procedure or function prAPIImportTagDeployments has too many arguments specified.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:314)
	at org.bsc.SQLCallableStmt.executeUpdate(SQLCallableStmt.java:596)
	at org.bsc.motus.servlets.TagsAPI.deployTag(TagsAPI.java:401)
	at org.bsc.motus.servlets.TagsAPI.processRequest(TagsAPI.java:103)
	at org.bsc.motus.servlets.TagsAPI.doPost(TagsAPI.java:727)

**Comment by pmorrill** [comment]
The code also tried to add the status code to the PROC; but we removed that from the PROC some time ago (it now has 19 parameters); I've adjusted in both beta3 and sandbox;
