### ISSUE TITLE
SQL error on API tag deployments query

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#72]
There's a small error here (missing alias on tagDeployID) which will need fixing. I looked into it, but the where part is generated separately, and I not yet sure that adding the table alias there (TagBean.buildStatusClause) would not create problems elsewhere if the tables aren't being aliases the same way.

I was at first confused also by the table join (the template_short is already a subset of the template, with fewer fields), but I see that the where fields are only in the full version. Adding a join adds a bit of overhead, but there are small tables, so it probably doesn't matter.

-----Original Message-----

Error type = 7 - Low-level Database error
Error Code = 209
SQL = SELECT a.* FROM vwBase_API_tag_deployments_template_short a  JOIN vwBase_API_tag_deployments_template b ON a.tagDeployID = b.tagDeployID  WHERE a.tagProjectID = ? AND **tagDeployID** is not null AND tsStart IS not null AND tsStart < 1505894834889 AND (tsEnd is null or tsEnd > 1505894834889) AND speciesID IS NOT NULL 
Description = sql passthru tags (Made it to result set wrapper)

Browser info:Unknown
Auth type = Unknown
Method = Unknown
Query = Unknown
Uri = Unknown
All parameters:Unknown
Stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: Ambiguous column name 'tagDeployID'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
	at org.bsc.SQLPreparedStmt.executeQuery(SQLPreparedStmt.java:246)
	at org.bsc.motus.servlets.TagsAPI.buildTagsTemplate(TagsAPI.java:282)
	at org.bsc.motus.servlets.TagsAPI.processRequest(TagsAPI.java:85)
	at org.bsc.motus.servlets.TagsAPI.doGet(TagsAPI.java:713)

**Comment by pmorrill** [comment]
Should be resolved in sandbox and beta3 on next build
